query GetMatches {
  matches {
    payload {
      id
      initiatorUserId
      requestedUserId
      status
      createdAt
      updatedAt
      initiator {
        id
        firstName
        lastName
        username
      }
    }
  }
}